### ISSUE TITLE
4.0.0 fails to start with db error for on_pause

### ISSUE THREAD

**Issue by kasper79** [hassio-addons/addon-tautulli#325]
# Problem

2023-12-08 08:01:40 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
2023-12-08 08:01:40 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/Tautulli.py", line 324, in <module>
    main()
  File "/opt/Tautulli.py", line 247, in main
    plexpy.start()
  File "/opt/plexpy/__init__.py", line 572, in start
    notifiers.check_browser_enabled()
  File "/opt/plexpy/notifiers.py", line 4484, in check_browser_enabled
    for n in get_notifiers():
             ^^^^^^^^^^^^^^^
  File "/opt/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
             ^^^^^^^^^^
  File "/opt/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
                 ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: ambiguous column name: on_pause

Traceback (most recent call last):
  File "/opt/Tautulli.py", line 324, in <module>
    main()
  File "/opt/Tautulli.py", line 247, in main
    plexpy.start()
  File "/opt/plexpy/__init__.py", line 572, in start
    notifiers.check_browser_enabled()
  File "/opt/plexpy/notifiers.py", line 4484, in check_browser_enabled
    for n in get_notifiers():
             ^^^^^^^^^^^^^^^
  File "/opt/plexpy/notifiers.py", line 510, in get_notifiers
    result = db.select(
             ^^^^^^^^^^
  File "/opt/plexpy/database.py", line 455, in select
    sql_results = self.action(query, args).fetchall()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/plexpy/database.py", line 433, in action
    sql_result = c.execute(query, args)
                 ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: ambiguous column name: on_pause

## Expected behavior

To start up properly.

## Actual behavior

fails to start with sqlite3.OperationalError: ambiguous column name: on_pause

## Proposed changes

This is on a Intel Nuc running add-on 4.0.0

**Comment by kolossboss** [comment]
Same error, also with Intel Nuc

**Comment by stefsims** [comment]
Same...
